### ISSUE TITLE
where the fuck is the doc ?!

### ISSUE THREAD

**Issue by Clm-Roig** [thaisaurard/graphJava#2]
all is in the title :-1: 

see you later little pickle :pig:

**Comment by thaisaurard** [comment]
I see you are so angry you can't have a proper conversation. In order to make you gentler, i added the doc files in the jar archive. Hope you will have a lot of joy in your life !

**Comment by Clm-Roig** [comment]
No thank you :hankey: 
May your dog die of cancer :dog: :arrow_right: :skull_and_crossbones:

**Comment by thaisaurard** [comment]
Leave my lovely golden retriever out of this or I'm gonna break your two legs.

**Comment by Clm-Roig** [comment]
I see you are so angry you can't have a proper conversation. In order to make you gentler, I send you this => :heart: :heart: :heart: :heart: . Hope you will have a lot of joy in your life ! :peace_symbol: :heart:

**Comment by thaisaurard** [comment]
I forgive you let's all rejoice and make love and smoke weed

**Comment by Clm-Roig** [comment]
You junky methhead, go burn in hell :fire: :skull:

**Comment by thaisaurard** [comment]
I see you are so angry you can't have a proper conversation. In order to make you gentler, i added the doc files in the jar archive. Hope you will have a lot of joy in your life ! :peace_symbol: :heart:

**Comment by Clm-Roig** [comment]
Oh great, thank you very much, I love you :heart: 
Go fuck a cow now please :cow:

**Comment by thaisaurard** [comment]
roger that, prepare your ass

**Comment by Clm-Roig** [comment]
who the fuck is roger ? :confused:

**Comment by thaisaurard** [comment]
ask your mom

**Comment by Clm-Roig** [comment]
:notes: Mamaaaaaaaaaaaaaaaaaaaaaa, whohouhouhou (is roger ?) :notes:
